functional:
   - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
   - Пользователь должен иметь возможность фильтровать товары
   - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
   - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
   
non-functional:
   - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
   - Сайт должен быть безопасным и защищать данные пользователя
   - Сайт должен иметь мобильную версию
   - Сайт должен быть протестирован на совместимость с последними версиями браузеров
   - Сайт должен быть способен обрабатывать большое количество трафика
   - Сайт должен быть доступен на различных устройствах

implicit:
   - при оформленим заказа пользователь должен быть зарегистрирован и авторизован
   - при оформлении заказа у пользователя должны быть указаны контактные данные
   - цена товара не может быть  нулем или отрицательным числом
   - количество товара не может быть отрицательным числом
   - количество товара не может быть дробным
   - нельзя положить в корзину товар, если его количество равно 0
